# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.network :private_network, type: "dhcp"
  config.vm.hostname = "poleen"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
  end
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../provisioning/playbook.yml"
  end
end
