---
- hosts: all
  become: True
  gather_facts: True
  roles:
    - general-dependancies
    - ansible-role-vagrant
    - ansible-pip
    - python-packages
    - ansible-vim
    - ansible-role-sublimetext
    - config-files
